# Generated by Django 4.1 on 2022-09-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Page",),
    ]
