# Generated by Django 4.1 on 2022-08-31 14:26

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_cover_image_product_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_images",
            name="images",
            field=models.ImageField(
                blank=sqlalchemy.sql.expression.true, upload_to="../products/images"
            ),
        ),
    ]
