# Generated by Django 4.1 on 2022-08-31 14:37

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_images_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_images",
            name="images",
            field=models.ImageField(
                blank=sqlalchemy.sql.expression.true, upload_to="images"
            ),
        ),
    ]
