# Generated by Django 4.1 on 2022-09-12 06:25

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_product_images_images"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="cover_image",),
        migrations.RemoveField(model_name="product_images", name="product",),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product_images",
            ),
        ),
        migrations.AlterField(
            model_name="product_images",
            name="images",
            field=models.ImageField(
                blank=sqlalchemy.sql.expression.true, null=True, upload_to="images"
            ),
        ),
    ]
