# Generated by Django 4.1 on 2022-09-12 07:48

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_remove_product_cover_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="images",),
        migrations.AddField(
            model_name="product",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="coverimages/"),
        ),
        migrations.AddField(
            model_name="product_images",
            name="product",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product_images",
            name="images",
            field=models.ImageField(
                blank=sqlalchemy.sql.expression.true, upload_to="images"
            ),
        ),
    ]
